jwt:
  lifetime: 30m

spring:
  mvc:
    cors:
      enabled: true
      allowed-origins: https://localhost:3000
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"
      exposed-headers: Authorization
      allow-credentials: true
      max-age: 3600
  datasource:
    url: postgres://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:railway}
    password: ${PGPASSWORD:*c15Adb4*g*4c5aD21GBC-dad36-35-1}
    username: ${PGUSER:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
